# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automation deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "https://github.com/anathatech/wallet-release-test/releases/download/v1.0.14/Anatha-1.0.14.dmg"
          target: public/
          
      - name: Install Anatha app
        run: |
          ls
          pwd
          cd Public
          pwd
          hdiutil attach Anatha-1.0.14.dmg
          cd /Volumes/Anatha\ 1.0.14/
          pwd
          mv "Anatha.app" /Applications/
          pwd
        continue-on-error: true
      - name: Open Anatha
        run: |
          sudo spctl --master-disable
          open -a Anatha
        continue-on-error: true
          
      - run: mkdir <dmg_root>
      - run: hdiutil attach public/Anatha-1.0.14.dmg -mountpoint mydirectory
      - run: sudo installer -pkg <dmg_root>/Install.pkg -target LocalSystem
      - run: hdiutil detach <dmg_root>
      
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
